apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: main
    alb.ingress.kubernetes.io/scheme: internet-facing
  labels:
{{ toYaml .Values.ingress.labels | indent 4 }}
  name: {{ template "fullname" .}}-socks-ingress
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: front-end
            port:
              number: 80
        path: /
        pathType: Prefix
    {{- if .Values.host }}
    host: {{ template "host" . }}
    {{- end }}
  {{- if .Values.ingress.tlsSecretName }}
  tls:
  - secretName: {{ .Values.ingress.tlsSecretName }}
    {{- if .Values.host }}
    hosts:
    - {{ template "host" . }}
    {{- end }}
  {{- end }}
